### ISSUE TITLE
You are not allowed to define new elements for path "security.firewalls".

### ISSUE THREAD

**Issue by SylDanh** [ecphp/cas-bundle#4]
hi,

i got a error using this bundle.

## Steps required to reproduce the problem

1. fresh install of symfony (symfony new my_project_name --full)
2. create one controller
3. install "ecphp /cas-bundle" following [installation doc](https://ecphp-cas-bundle.readthedocs.io/en/latest/pages/installation.html)
4. visit the website.

## Actual Result

*  HTTP 500 Internal Server Error  
You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.

![Screenshot_2020-04-25 You are not allowed to define new elements for path security firewalls Please define all elements for](https://user-images.githubusercontent.com/35763563/80277462-64858880-86ef-11ea-8819-780cdb253291.png)

Thanks.

**Comment by drupol** [comment]
Hello @SylDanh,

Thanks for using my package. I just tried and there is indeed something to fix there.
I will probably dedicate some time to fix this next week.

In the meantime, if you want to fix this quickly, copy the content of the file `vendor/cas-bundle/Resources/config/packages/dev/cas_security.yaml` into `my_project_name/config/packages/security.yaml`.
Make sure to manually merge the files properly and it should work.

Let me know how it goes!

**Comment by SylDanh** [comment]
Hello

After looking around a bit, that's what I did. And it worked.
But at least, now I know that what i did was not a mistake.

Thanks.

**Comment by drupol** [comment]
Excellent!

I'm glad to see it worked :)
Feel free to let us know how it goes and if this package fulfilled your expectations.

I'm not going to close the issue, I will keep it open until the documentation is updated.

**Comment by drupol** [comment]
The documentation has been updated, now it should not fail when copying the files.
Closing the issue now, feel free to reopen it.
