### ISSUE TITLE
Get rid of sensio/framework-extra-bundle

### ISSUE THREAD

**Issue by drupol** [ecphp/cas-bundle#43]
We currently need to rely on sensio/framework-extra-bundle to provide the necessary interface wiring to the nyholm/psr7 package.

Since the new version 6, those wiring are now gone.

We need to find a way to continue using this package without sension/framework-extra-bundle. 

Relates to https://github.com/ajgarlag/psr-http-message-bundle/pull/5

**Comment by Punt13140** [comment]
Hi,

I don't know if it's related...

I just started a new 5.3 project.
Right after installing the skeleton, I tried to install your bundle and I have an error

`You have requested a non-existent service "sensio_framework_extra.psr7.http_message_factory".`

**Comment by drupol** [comment]
Yes, this is indeed related. Going to check this and provide some feedback.

**Comment by drupol** [comment]
Hi,

It's removed on `master` branch, could you please test the master branch? If it works, I'll tag/bump a new release.

`composer require ecphp/cas-bundle:dev-master`

You might set `minimum-stability` and `prefer-stable` properties to `dev` and `true` respectively  to `composer.json`.

**Comment by Punt13140** [comment]
Hey,

Thanks for the quick response !

So I follow your instructions. It fixed the installation.

But then, I have 2 problems : 

1. When you follow the installation instruction, you ask to edit "config/packages/security" on step 2.

```
    firewalls:
        main:
            anonymous: ~
            guard:
                provider: cas
                authenticators:
                    - cas.guardauthenticator
```

You have one error : `The authenticator manager no longer has "anonymous" security. Please remove this option under the "main" firewall.`

So I removed anonymous and it's fixed.

2.  Then I have this error : 
`Cannot autowire service "cas": argument "$uriFactory" of method "EcPhp\CasLib\Cas::__construct()" references interface "Psr\Http\Message\UriFactoryInterface" but no such service exists. You should maybe alias this interface to the existing "psr18.http_client" service.`

**Comment by drupol** [comment]
That's a good feedback, thanks!

cas-bundle/cas-lib requires a [psr17](https://www.php-fig.org/psr/psr-17/) implementation, to fix that, just do:

`composer require loophp/psr17`

Let me know if this has fixed your issue, I'll update everything accordingly.

**Comment by Punt13140** [comment]
I first had to install 
`composer require nyholm/psr7` 
as suggested in [loophp/psr17](https://github.com/loophp/psr17) installation.

Then `composer require loophp/psr17 `, I changed the base_url to https://casserver.herokuapp.com/cas and it works !

**Comment by drupol** [comment]
Nice ! On next Monday I'm going to update the `composer.json`, documentation and so on.

**Comment by Punt13140** [comment]
Thanks for the quick feedbacks and solutions !

**Comment by drupol** [comment]
you're welcome!

**Comment by drupol** [comment]
Dear @Punt13140,

I'm giving a second look at this right now.
I don't think `loophp/psr17` is needed for now. Could you please try to remove the package and see if everything still works?

Thanks!

**Comment by Punt13140** [comment]
Hey,

Sorry I've been busy.

So I removed
```
        "loophp/psr17": "^1.0",
        "nyholm/psr7": "^1.4",
```

from `composer.json` and then `composer update`.

And I have this error `Attempted to load class "Psr17Factory" from namespace "Nyholm\Psr7\Factory".
Did you forget a "use" statement for another namespace?`.

I'm on `master` branch.

**Comment by drupol** [comment]
No, can you please only remove `loophp/psr17` and give me the full error ? (a screenshot is fine as well!)

**Comment by Punt13140** [comment]
It works !

**Comment by drupol** [comment]
Riiiight, `loop hp/psr17` is not needed for now, that's what I thought!

Thanks a lot for your assistance, I will update the packages accordingly in the upcoming days.

**Comment by Punt13140** [comment]
Hi @drupol,
Sorry I forgot to reply. You can close this issue.

Thanks
