### ISSUE TITLE
How to load custom / existing User entities instead of CasUser ?

### ISSUE THREAD

**Issue by luminouw** [ecphp/cas-bundle#56]
Hello,

I am adding the bundle to an existing project (Symfony 5.3) with existing users based on the default Symfony user entities.

So far I am able to protect the pages I want with a CAS auth, being redirected to the CAS server and then back to my app with the security token validated. In the Symfony profiler toolbar I can see the user I used on the CAS server as authenticated with the role "ROLE_CAS_AUTHENTICATED".

However my app then fails because I'm using methods to get user preferences (`$this->getUser()->getPrefs();`) which obviously aren't implemented in the CasUser class (`Attempted to call an undefined method named "getTexts" of class "EcPhp\CasBundle\Security\Core\User\CasUser"`). The current provider loads my users via their email attribute (and the CAS server I'll use will only return the email when auth is successful).

Is there any way to specify which User entity to load when authentication is ok ? And can it be done with some configuration options or do I need to write a couple of specific files (providers etc ...)

Thank you and thanks for your work : )

**Comment by luminouw** [comment]
Hello,

We finally ended up rewriting a very basic authenticator with the help of your cas-lib but without the use of Guard as we moved the projet to Symfony 5.4 and this has been marked as deprecated for future Symfony releases.

Should have closed this earlier, my bad as well : )

**Comment by drupol** [comment]
Ok ! Sorry again for the delay and glad you found out a solution in the end.

I'm currently working on an updated version of cas-bundle for symfony >= 5.4 as well.
