### ISSUE TITLE
Symfony 5.1 compatibility

### ISSUE THREAD

**Issue by drupol** [ecphp/cas-bundle#7]
In Symfony 5.1, the security and especially the Guard system has been revamped.

Read: 
* https://symfony.com/blog/new-in-symfony-5-1-updated-security-system
* http://wouterj.nl/2020/04/authenticators-new-symfony-security

This issue is to keep track of the evolution and compatibility of this package with Symfony 5.1.

I had a conversation with @wouterj on Slack and this is the outcome:
* Deprecated the custom Guard provided by this package, deprecated in favor of the new system.
* Both mechanism will be available in until the Guards are removed from Symfony (removed in Symfony 6)

**Comment by MICSCHWA** [comment]
Hi, I'm using your bundle for project together with Symfony 5.1. and got the deprecated message:

The "EcPhp\CasBundle\Security\CasGuardAuthenticator" class implements "Symfony\Component\Security\Http\Logout\LogoutSuccessHandlerInterface" that is deprecated since Symfony 5.1.

... however, I see that you already take care of the compatibility. Great job.

**Comment by drupol** [comment]
Hi,

Thanks for using the package! It's great to see that it's used by some other people :)

I did the branch because I also had the issue :)

I'm planning to dedicate some hours next week to finish this PR and tag a new version with full Symfony 5 and 5.1 support.

**Comment by jraller** [comment]
Is a release including the 5.1 functionality likely in the near future?

**Comment by drupol** [comment]
It's already compatible wit Symfony 5.1, there are some deprecated interfaces, but nothing that could be problematic.

Have you tried the latest release so far?

**Comment by drupol** [comment]
@jraller Any feedback to share?

**Comment by jraller** [comment]
I haven't had luck configuring it for use with API Platform 2.6+ on Symfony 5.2 yet. I've still got tests to run. The use of Caddy for the front end complicates things as by default only certain routes are handled by Symfony. I'll follow up when I know more.

**Comment by drupol** [comment]
Allrighty feel free to open issues, I'll do my best to help.

I also confirm that the package works for Symfony `>=5.1`.

**Comment by drupol** [comment]
Closing this issue, feel free to reopen it if you feel that something is wrong.
