### ISSUE TITLE
Cannot set an entry point

### ISSUE THREAD

**Issue by ElKhattoutiMohamed** [ecphp/cas-bundle#75]
Hello, I am trying to develop a small web app that should require the user to be connected using the CAS authenticator in order to access protected ressources.

However, I don't really understand how to redirect the user to the CAS login page since there is no entry point used in the security.yaml file. 
I followed the instructions specified here : https://ecphp-cas-bundle.readthedocs.io/en/latest/pages/installation.html
However, i am not redirected direclty to the CAS login page.

Is there a class that acts as an entry point in the bundle or should I create one myself?

My security.yaml file : 
![image](https://user-images.githubusercontent.com/98489881/205657773-e1eb8846-ab48-4a69-8983-19bf730434f7.png)

security:
    &emsp;enable_authenticator_manager: true
    &emsp;firewalls:
        &emsp;&emsp;dev:
           &emsp;&emsp;&emsp; pattern: ^/(_(profiler|wdt)|css|images|js)/
           &emsp;&emsp;&emsp; security: false
       &emsp;&emsp; main:
            &emsp;&emsp;&emsp;lazy: true
&emsp;&emsp;&emsp;\#            provider: users_in_memory
           &emsp;&emsp;&emsp; custom_authenticator:
           &emsp;&emsp;&emsp;&emsp;     - EcPhp\CasBundle\Security\CasAuthenticator
   &emsp;access_control:
       &emsp;&emsp; - { path: ^/securedRessource, role: ROLE_CAS_AUTHENTICATED }
&emsp;providers:
        &emsp;&emsp;\# used to reload user from session & other features (e.g. switch_user)
        &emsp;&emsp;app_user_provider:
            &emsp;&emsp;&emsp;entity:
               &emsp;&emsp;&emsp;&emsp; class: App\Entity\User
               &emsp;&emsp;&emsp;&emsp; property: email

Thank you for the reply.

**Comment by drupol** [comment]
Hi !

Can you please share some numbers like:

- Symfony version
- CAS Lib version
- CAS Bunle version

`composer show` is your friend for this.

Thanks!

**Comment by ElKhattoutiMohamed** [comment]
Hi !
Here are the different versions asked :

symfony version                              Symfony 6.1.8
ecphp/cas-lib                                   1.1.9   CAS Lib, a standard library for CAS authentication.
ecphp/ecas                                      2.3.0   CAS library to communicate with ECAS / EU Login

Hope that helps

**Comment by drupol** [comment]
Thanks, all good there.

Now, what is happening when you try to go to `/securedResource` ?

Thanks.

**Comment by drupol** [comment]
Right, I'm going to make a reproducer locally, let me get back to you on Wednesday.

**Comment by ElKhattoutiMohamed** [comment]
Alright, thank you very much for the help !

**Comment by drupol** [comment]
You're welcome.

In the meantime, here's [a demo app](https://github.com/drupol/cas-bundle-demo) that was working fine, maybe you can get some inspirations.

**Comment by ElKhattoutiMohamed** [comment]
Hi, I finally managed to make this work : 

1. My security.yaml file:        
 ```
security:
    enable_authenticator_manager: true
    firewalls:
        main:
            form_login: ~
            custom_authenticator: EcPhp\CasBundle\Security\CasAuthenticator
            entry_point : form_login

    access_control:
        - { path: ^/securedRessource, role: ROLE_CAS_AUTHENTICATED }
```
2. Added a (/login) path in my Controller : 
```
    /**
     * @Route("/login", name="app_login")
     */
    public function login(Request $request)
    {
        return $this->cas->login();
    }
```

Thanks for your help.

**Comment by drupol** [comment]
Ho good !

There is already a login controller that you should use instead so you don't have to create one. It's in CAS Bundle.

**Comment by ElKhattoutiMohamed** [comment]
Issue is closed, thanks for the assistance.
