### ISSUE TITLE
Other provider

### ISSUE THREAD

**Issue by bpierrot** [ecphp/cas-bundle#78]
## Steps required to reproduce the problem

Is there a way to use another provider than the cas provider such as user provider or ldap provider?

    providers:
        user_provider:
            entity:
                class: 'App\Entity\User'
                property: username

        main:
            provider: user_provider

![image](https://user-images.githubusercontent.com/2832559/220981638-b8f18d94-3a85-4079-81ac-34d4929f6a24.png)

-

**Comment by drupol** [comment]
Hello!

The `CasAuthenticator`  service is being injected a default user provider, so it is fully possible to decorate it with your own and implements your custom logic and user.

Let me know if you need further help.

**Comment by drupol** [comment]
Dear @bpierrot,

Did my answer helped you?
