### ISSUE TITLE
Tag downgrade

### ISSUE THREAD

**Issue by Punt13140** [ecphp/cas-bundle#80]
Hi,

I was looking at the changes you are currently doing to your bundle, 
and I noticed you were tagging on 2.4.* and in December you were on 2.5.*

Is this intentional?

**Comment by drupol** [comment]
Hi,

Yes, I maintain multiple branches of this bundle.

* 2.3 is for Symfony ^4 || ^5 (CasLib v1)
* 2.4 is for Symfony ^5.4 || ^6 (CasLib v1)
* 2.5 is for Symfony ^6 (CasLib v1)
* 3.0 is for Symfony ^6 but with CasLib v2

**Comment by Punt13140** [comment]
Ok. My bad.
I didn't want you to keep pushing the tags if it was a mistake.
I'm closing.

Thanks.

**Comment by drupol** [comment]
No problem :)

There has been a problem yesterday since we are using multiple remotes (Github and code.europa.eu) but users should not have any impact.

Basically one of the remote I created the new tag on was not in sync with its counterpart and this created a couple of issues.
