### ISSUE TITLE
Client fetch requests for a secured API route returns 302 redirect when already logged in

### ISSUE THREAD

**Issue by bljohnsondev** [ecphp/cas-bundle#82]
## Steps required to reproduce the problem

1. Using a browser fetch (axios, etc) make an API call to a secured route
2. Secured route redirects to CAS even when the user is already logged in
3. API call fails

## Expected Result

- If already logged in skip the 302 redirect

## Actual Result

- API call fails

Is every secured route redirected to CAS even when the user is logged in?  When making an API call from the browser to a route that is secured it fails because the API call is being redirected to CAS.  Is there a workaround for this or is this library not suitable for securing API endpoints?

**Comment by drupol** [comment]
Hello,

Using CAS to make an API call is not appropriate since making an API call is usually stateless.

It is possible to use this library to do that, but you have to use proxy tickets and I need to refresh my memory about this since I don't use it that often.

**Comment by bljohnsondev** [comment]
Well it *could* work if the API call returned a 302 or 401 if the user wasn't already logged in (or if I could trap that and return a JSON response notifying the frontend that the user isn't authorized).  If the user was already logged in it would return the expected JSON response without the redirect.  However, if that's not the intended use I'll have to figure out a workaround.

Thanks for the reply, though!

**Comment by bljohnsondev** [comment]
Will do!  Thanks for looking into it.

**Comment by drupol** [comment]
Very nice !!! Thanks for letting me know :)
