### ISSUE TITLE
Making the Locale "Sticky" during a User's Session

### ISSUE THREAD

**Issue by alixcertem** [ecphp/cas-bundle#86]
Hello, not a bug but a question. 
I use actually l3/cas-bundle and the locale "sticky" during user's session doesn't work (see doc for example : https://symfony.com/doc/5.4/session.html#making-the-locale-sticky-during-a-user-s-session). Have you try this feature on your bundle ? and if yes, does it work ?
Thank in advance.

**Comment by drupol** [comment]
Hello Alix,

Thanks for your interest in this bundle.

Fortunately, this bundle doesn't modify the user session, the framework is doing it for us. That is the reason why we are using an [Authenticator](https://github.com/ecphp/cas-bundle/blob/ee907aec56e78092f17c5c5e263fb6322467b3c4/src/Security/CasAuthenticator.php).

Therefore, the feature you're asking us is out of scope here and it's not up to this bundle to take care of it.

Feel free to reopen the issue if you have more question.

Have a good day.

**Comment by alixcertem** [comment]
Hello Drupol,

Thanks for your fast response. Can you tell me how do you use the session user with your application/framework ? I am interesting if you have a solution for that.

Thanks in advance.

**Comment by drupol** [comment]
I just let the Authenticator do it's job and then you can [retrieve the authenticated user](https://symfony.com/doc/current/security.html#fetching-the-user-from-a-service) everywhere in the application.

We actually do not manipulate the session.

**Comment by alixcertem** [comment]
Ok, thanks. You tell "do not manipulate the session", but in your bundle, after authentification, can i load page by using custom locale, for example defined by the user in her profile ? Not to mention session.

Thanks in advance.

**Comment by alixcertem** [comment]
Ok, thanks.
