### ISSUE TITLE
Fix in CasAuthenticator 2.4.5, syntax error, unexpected ')', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by jjbier** [ecphp/cas-bundle#94]
In https://github.com/ecphp/cas-bundle/blob/2.4.5/src/Security/CasAuthenticator.php#L49

The constructor has a comma in the last parameter

**Comment by drupol** [comment]
Hi !

I invite you to update your PHP version, see https://php.watch/versions/8.0/trailing-comma-parameter-use-list

Have a good day.
